#!/bin/bash
set -e

# PlainSight Raspberry Pi Installation Script
# This script provisions a fresh Raspberry Pi for PlainSight digital plainsight

echo "================================================"
echo "  PlainSight Digital Signage Player Installer"
echo "================================================"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
  echo "Please do not run as root. Run as pi user."
  exit 1
fi

# Read server IP
read -p "Enter the PlainSight Server IP address: " SERVER_IP
if [ -z "$SERVER_IP" ]; then
  echo "Server IP is required"
  exit 1
fi

# Read SMB details
echo ""
echo "SMB Share Configuration:"
read -p "Enter SMB Host (e.g., MyCloud.local): " SMB_HOST
read -p "Enter SMB Share and Path (e.g., corona/PlainSight): " SMB_PATH
read -p "Enter SMB username: " SMB_USER
read -sp "Enter SMB password: " SMB_PASSWORD
echo ""

if [ -z "$SMB_HOST" ] || [ -z "$SMB_PATH" ] || [ -z "$SMB_USER" ] || [ -z "$SMB_PASSWORD" ]; then
  echo "All SMB configuration fields are required"
  exit 1
fi

# 1. Update system
echo "Updating system packages..."
sudo apt update
sudo apt upgrade -y

# 2. Install dependencies
echo "Installing required dependencies..."
sudo apt install -y \
  chromium \
  labwc \
  wayland-protocols \
  cifs-utils \
  grim \
  swayidle \
  swaybg \
  wlopm \
  unclutter \
  libgdiplus \
  curl

# 3. Create directories
echo "Creating application and cache directories..."
sudo mkdir -p /opt/plainsight
sudo mkdir -p /mnt/plainsight
sudo mkdir -p /var/cache/plainsight/content
sudo mkdir -p /var/cache/plainsight/idle
sudo mkdir -p /etc/samba
sudo chown -R pi:pi /opt/plainsight
sudo chown -R pi:pi /var/cache/plainsight

# 4. Download Player Binary (Bootstrap)
echo ""
echo "WARNING: Downloading binary over HTTP (no integrity verification)"
echo "For production, use HTTPS and verify checksums/signatures"
echo ""
read -p "Continue? (y/n): " CONTINUE
if [ "$CONTINUE" != "y" ]; then
  echo "Installation aborted"
  exit 1
fi

echo "Downloading PlainSight Player..."
curl -L "http://${SERVER_IP}:8080/api/updates/latest/binary" -o /opt/plainsight/PlainSight.Player
chmod +x /opt/plainsight/PlainSight.Player

# 5. Create SMB credentials file
echo "Creating SMB credentials file..."
sudo bash -c "cat > /etc/samba/plainsight-credentials << EOF
username=${SMB_USER}
password=${SMB_PASSWORD}
EOF"
sudo chmod 600 /etc/samba/plainsight-credentials

# 6. Configure systemd units
echo "Configuring systemd services..."

# SMB mount (stays as system unit)
sudo bash -c "cat > /etc/systemd/system/mnt-plainsight.mount << EOF
[Unit]
Description=Mount Remote Signage Assets
After=network-online.target

[Mount]
What=//${SMB_HOST}/${SMB_PATH}
Where=/mnt/plainsight
Type=cifs
Options=credentials=/etc/samba/plainsight-credentials,rw,vers=3.0,uid=1000,gid=1000

[Install]
WantedBy=multi-user.target
EOF"

# Automount (stays as system unit)
sudo bash -c "cat > /etc/systemd/system/mnt-plainsight.automount << EOF
[Unit]
Description=Automount Signage Share

[Automount]
Where=/mnt/plainsight
TimeoutIdleSec=0

[Install]
WantedBy=multi-user.target
EOF"

# PlainSight player service (User Unit)
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/plainsight.service << EOF
[Unit]
Description=PlainSight Digital Signage Player
After=network-online.target
# We don't depend on mnt-plainsight.mount here because it's a system unit,
# but the player will handle the path being missing gracefully.

[Service]
Type=simple
WorkingDirectory=/opt/plainsight
ExecStart=/opt/plainsight/PlainSight.Player
Restart=always
RestartSec=3
Environment=DISPLAY=:0
Environment=WAYLAND_DISPLAY=wayland-0
Environment=XDG_RUNTIME_DIR=/run/user/1000
Environment=DOTNET_CLI_TELEMETRY_OPTOUT=1
Environment=ServerUrl=http://${SERVER_IP}:8080
Environment=PLAINSIGHT_APIKEY_PATH=/var/cache/plainsight/apikey

[Install]
WantedBy=default.target
EOF

# 6. Configure labwc
echo "Configuring labwc window manager..."
mkdir -p ~/.config/labwc

cat > ~/.config/labwc/rc.xml << 'EOF'
<labwc_config>
  <windowRules>
    <windowRule identifier="PlainSight.Player">
      <action name="ToggleFullscreen" />
    </windowRule>
  </windowRules>
</labwc_config>
EOF

cat > ~/.config/labwc/autostart << 'EOF'
#!/bin/bash
# Show custom splash image while the player starts up.
# The splash is auto-generated by the PlainSight Player on first run.
# To use a custom image, replace /opt/plainsight/splash.png with your own 1920x1080 PNG before first boot.
SPLASH=/opt/plainsight/splash.png
if [ -f "$SPLASH" ]; then
  swaybg -i "$SPLASH" -m fill &
else
  swaybg -c 0a0a14 &
fi

# Disable screen sleep/power saving
swayidle -w timeout 31536000 'wlopm --off \*' resume 'wlopm --on \*' &

# Hide the X11 cursor as soon as XWayland is available.
# labwc starts XWayland before running autostart, but add a brief wait as safety.
(WAIT=0; while [ ! -S /tmp/.X11-unix/X0 ] && [ "$WAIT" -lt 10 ]; do sleep 0.2; WAIT=$((WAIT+1)); done; unclutter -display :0 -idle 0.1 -root) &
EOF

chmod +x ~/.config/labwc/autostart

# Create the display startup script that KioskService calls at runtime.
# It waits for XWayland to be ready, then launches Chromium on the physical screen.
cat > /opt/plainsight/start-player.sh << 'EOF'
#!/bin/bash
set -e

# Kill any stale Chromium from a previous run
pkill -f chromium || true

# Wait up to 30 s for labwc to expose the XWayland socket
WAIT=0
while [ ! -S /tmp/.X11-unix/X0 ] && [ "$WAIT" -lt 30 ]; do
    sleep 1
    WAIT=$((WAIT + 1))
done

if [ ! -S /tmp/.X11-unix/X0 ]; then
    echo "ERROR: XWayland socket /tmp/.X11-unix/X0 not available after 30 s" >&2
    exit 1
fi

# Hide the X11 cursor (parked at 0,0 with no mouse on a kiosk display).
# Runs on DISPLAY=:0 (XWayland) so it hides the compositor-level cursor.
unclutter -display :0 -idle 0.5 -root &

# DISPLAY=:0 and WAYLAND_DISPLAY=wayland-0 are set by the systemd unit.
# Chromium renders via X11 → XWayland → labwc → physical HDMI.
chromium \
    --no-first-run \
    --kiosk \
    --ozone-platform=x11 \
    http://localhost:5555/player &
CHROMIUM_PID=$!

wait $CHROMIUM_PID
EOF
chmod +x /opt/plainsight/start-player.sh

# Suppress the login MOTD/banner on tty1 so it doesn't flash before labwc starts
touch ~/.hushlogin

# 7. Configure silent boot for signage displays
echo "Configuring silent boot..."

# Determine boot partition path (Bookworm uses /boot/firmware; older Pi OS uses /boot)
if [ -d "/boot/firmware" ]; then
  BOOT_DIR="/boot/firmware"
else
  BOOT_DIR="/boot"
fi

# Disable the GPU firmware rainbow splash shown before the kernel loads
CONFIG_FILE="$BOOT_DIR/config.txt"
if grep -q "^disable_splash" "$CONFIG_FILE"; then
  sudo sed -i 's/^disable_splash=.*/disable_splash=1/' "$CONFIG_FILE"
elif grep -q "^#disable_splash" "$CONFIG_FILE"; then
  sudo sed -i 's/^#disable_splash.*/disable_splash=1/' "$CONFIG_FILE"
else
  printf '\n# Suppress firmware boot splash\ndisable_splash=1\n' | sudo tee -a "$CONFIG_FILE" > /dev/null
fi

# Install Plymouth directly so we control the package before touching cmdline.txt.
# raspi-config do_boot_splash fails on a fresh image because Plymouth is not yet
# installed when it runs, which causes set -e to abort the script prematurely.
echo "Installing Plymouth (this may take a minute)..."
sudo apt-get install -y plymouth plymouth-themes

# Remove console=tty1 so the kernel and systemd write to the serial port only,
# not the HDMI display. Plymouth starts too late on Pi OS (no initramfs by
# default) to reliably intercept this output, so removing the binding is the
# only way to guarantee a clean screen. The autologin getty and labwc both use
# tty1 directly and are unaffected by this change.
# quiet + splash are added here because raspi-config do_boot_splash is skipped.
CMDLINE_FILE="$BOOT_DIR/cmdline.txt"
CMDLINE=$(cat "$CMDLINE_FILE")
CMDLINE=$(echo "$CMDLINE" | sed 's/\bconsole=tty[0-9]*\b//g' | sed 's/  */ /g' | sed 's/^ //')
for PARAM in quiet splash loglevel=0 logo.nologo vt.global_cursor_default=0; do
  if ! echo "$CMDLINE" | grep -qw "$PARAM"; then
    CMDLINE="$CMDLINE $PARAM"
  fi
done
echo "$CMDLINE" | sudo tee "$CMDLINE_FILE" > /dev/null

# Create PlainSight Plymouth theme — dark gradient with centered "PlainSight / Digital Signage" text
THEME_DIR="/usr/share/plymouth/themes/plainsight"
sudo mkdir -p "$THEME_DIR"

sudo tee "$THEME_DIR/plainsight.plymouth" > /dev/null << 'EOF'
[Plymouth Theme]
Name=PlainSight
Description=PlainSight Digital Signage
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/plainsight
ScriptFile=/usr/share/plymouth/themes/plainsight/plainsight.script
EOF

sudo tee "$THEME_DIR/plainsight.script" > /dev/null << 'EOF'
Window.SetBackgroundTopColor(0.05, 0.05, 0.10);
Window.SetBackgroundBottomColor(0.00, 0.00, 0.00);

title_image = Image.Text("PlainSight", 1.0, 1.0, 1.0);
sub_image   = Image.Text("Digital Signage", 0.60, 0.60, 0.65);

title_sprite = Sprite(title_image);
title_sprite.SetX(Window.GetWidth() / 2 - title_image.GetWidth() / 2);
title_sprite.SetY(Window.GetHeight() / 2 - title_image.GetHeight() - 8);
title_sprite.SetOpacity(1);

sub_sprite = Sprite(sub_image);
sub_sprite.SetX(Window.GetWidth() / 2 - sub_image.GetWidth() / 2);
sub_sprite.SetY(Window.GetHeight() / 2 + 8);
sub_sprite.SetOpacity(1);
EOF

echo "Applying PlainSight Plymouth theme (rebuilding initramfs, please wait)..."
sudo plymouth-set-default-theme -R plainsight

# 8. Enable services
echo "Configuring boot target, autologin, and enabling services..."
sudo systemctl set-default graphical.target
sudo raspi-config nonint do_boot_behaviour B2

# Ensure labwc starts on tty1 login; clear the screen first to wipe the agetty
# login line before the compositor renders its first frame.
if ! grep -q "exec labwc" ~/.bash_profile 2>/dev/null; then
  cat >> ~/.bash_profile << 'EOF'
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    printf "\033c"
    exec labwc
fi
EOF
fi

# Suppress tty1 login text so nothing is visible before labwc takes the screen.
# /etc/issue and /etc/issue.d/IP.issue are shown by agetty before autologin.
sudo truncate -s 0 /etc/issue
sudo truncate -s 0 /etc/issue.net
[ -f /etc/issue.d/IP.issue ] && sudo truncate -s 0 /etc/issue.d/IP.issue

# Silence getty@tty1 stdout/stderr so the "login: pi (automatic login)" line
# and any remaining agetty output never reach the HDMI display.
sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo tee /etc/systemd/system/getty@tty1.service.d/silent.conf > /dev/null << 'EOF'
[Service]
StandardOutput=null
StandardError=null
EOF

# Suppress login MOTD and /etc/profile.d banner scripts
touch ~/.hushlogin

sudo systemctl daemon-reload
sudo systemctl enable mnt-plainsight.automount
systemctl --user daemon-reload
systemctl --user enable plainsight.service
# Allow the player user service to start at boot without waiting for interactive login
sudo loginctl enable-linger pi
# Grant passwordless sudo so remote management tools can run privileged commands
echo 'pi ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/010_pi-nopasswd > /dev/null
sudo chmod 440 /etc/sudoers.d/010_pi-nopasswd

echo ""
echo "================================================"
echo "Installation Complete!"
echo "================================================"
echo ""
echo "The system will now reboot."
echo "After reboot, the PlainSight Player will start automatically."
echo ""
read -p "Press Enter to reboot now..."

sudo reboot
