#!/bin/bash
# PlainSight Photino Player Autostart Script for labwc

# Disable screen sleep/power saving
swayidle -w timeout 31536000 'wlopm --off \*' resume 'wlopm --on \*' &

# Start PlainSight Photino Player
/opt/signage/Signage.Player.Photino &
