#!/bin/bash
# PlainSight Player Autostart Script for labwc

# Solid black desktop so there is no flash between Plymouth exit and the player window appearing
swaybg -c 000000 &

# Disable screen sleep/power saving
swayidle -w timeout 31536000 'wlopm --off \*' resume 'wlopm --on \*' &
