// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlainSight.Server.Data;

#nullable disable

namespace PlainSight.Server.Migrations
{
    [DbContext(typeof(PlainSightDbContext))]
    [Migration("20260514210000_UpdateBrandingToNewFiles")]
    partial class UpdateBrandingToNewFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Model configuration would be auto-generated here
            // This is a placeholder for the model snapshot
#pragma warning restore 612, 618
        }
    }
}
