<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>90c4cac1-6f14-43ee-9669-9cf5f96bedcc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="PuppeteerSharp" Version="24.42.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="PlainSight.Server.Models" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlainSight.Shared\PlainSight.Shared.csproj" />
    <ProjectReference Include="..\PlainSight.ServiceDefaults\PlainSight.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Keys\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
